// Auto-generated by scripts/stamp-version.js — do not edit by hand.
export const BUILD_VERSION = "995c5fd.1780410050724";
export const BUILD_COMMIT  = "995c5fd";
export const BUILT_AT      = "2026-06-02T14:20:50.720Z";
