/*
 * Writes public/version.json with the current commit SHA + build time.
 *
 * Runs from the build step (see package.json). The file ships to the
 * deploy and is fetched by the app at boot to detect new versions.
 *
 * Sample output:
 *   { "commit": "849fab4", "builtAt": "2026-06-02T16:11:08.213Z" }
 */
const { execSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

function gitOut(cmd, fallback) {
  try { return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); }
  catch { return fallback; }
}

const commit = gitOut('git rev-parse --short HEAD', 'dev');
const builtAt = new Date().toISOString();
const versionTag = `${commit}.${Date.now()}`;

const target = path.resolve(__dirname, '..', 'public', 'version.json');
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, JSON.stringify({ commit, builtAt, version: versionTag }, null, 2) + '\n');
console.log(`Wrote ${target}\n  → ${versionTag}`);

// Also drop into a JS module that we import at runtime so the BUILT
// bundle knows its own commit hash without an extra fetch.
const constPath = path.resolve(__dirname, '..', 'src', 'config', 'buildVersion.js');
fs.writeFileSync(
  constPath,
  `// Auto-generated by scripts/stamp-version.js — do not edit by hand.\n` +
  `export const BUILD_VERSION = ${JSON.stringify(versionTag)};\n` +
  `export const BUILD_COMMIT  = ${JSON.stringify(commit)};\n` +
  `export const BUILT_AT      = ${JSON.stringify(builtAt)};\n`
);
console.log(`Wrote ${constPath}`);
