// US state food-insecurity rates (Feeding America, "Map the Meal
// Gap" 2022). Keyed by 2-digit FIPS code — the same key the
// world-atlas `states-10m` TopoJSON uses for feature IDs — so we
// can paint the US choropleth without a name-matching dance.
//
// Refresh: drop a new "Map the Meal Gap" CSV and re-run the import.
export const STATE_BY_FIPS = {
  '01': { code: 'AL', name: 'Alabama',        rate: 16.5 },
  '02': { code: 'AK', name: 'Alaska',         rate: 14.5 },
  '04': { code: 'AZ', name: 'Arizona',        rate: 13.0 },
  '05': { code: 'AR', name: 'Arkansas',       rate: 17.2 },
  '06': { code: 'CA', name: 'California',     rate:  9.7 },
  '08': { code: 'CO', name: 'Colorado',       rate: 10.0 },
  '09': { code: 'CT', name: 'Connecticut',    rate: 11.3 },
  '10': { code: 'DE', name: 'Delaware',       rate: 12.5 },
  '11': { code: 'DC', name: 'D.C.',           rate: 12.5 },
  '12': { code: 'FL', name: 'Florida',        rate: 13.6 },
  '13': { code: 'GA', name: 'Georgia',        rate: 13.6 },
  '15': { code: 'HI', name: 'Hawaii',         rate: 10.5 },
  '16': { code: 'ID', name: 'Idaho',          rate: 11.6 },
  '17': { code: 'IL', name: 'Illinois',       rate: 11.7 },
  '18': { code: 'IN', name: 'Indiana',        rate: 13.0 },
  '19': { code: 'IA', name: 'Iowa',           rate:  9.9 },
  '20': { code: 'KS', name: 'Kansas',         rate: 11.5 },
  '21': { code: 'KY', name: 'Kentucky',       rate: 14.2 },
  '22': { code: 'LA', name: 'Louisiana',      rate: 18.6 },
  '23': { code: 'ME', name: 'Maine',          rate: 12.6 },
  '24': { code: 'MD', name: 'Maryland',       rate: 11.6 },
  '25': { code: 'MA', name: 'Massachusetts',  rate:  9.6 },
  '26': { code: 'MI', name: 'Michigan',       rate: 12.8 },
  '27': { code: 'MN', name: 'Minnesota',      rate:  8.7 },
  '28': { code: 'MS', name: 'Mississippi',    rate: 19.5 },
  '29': { code: 'MO', name: 'Missouri',       rate: 13.0 },
  '30': { code: 'MT', name: 'Montana',        rate: 12.0 },
  '31': { code: 'NE', name: 'Nebraska',       rate: 10.0 },
  '32': { code: 'NV', name: 'Nevada',         rate: 11.3 },
  '33': { code: 'NH', name: 'New Hampshire',  rate:  9.6 },
  '34': { code: 'NJ', name: 'New Jersey',     rate:  9.5 },
  '35': { code: 'NM', name: 'New Mexico',     rate: 14.6 },
  '36': { code: 'NY', name: 'New York',       rate: 11.5 },
  '37': { code: 'NC', name: 'North Carolina', rate: 13.6 },
  '38': { code: 'ND', name: 'North Dakota',   rate:  9.0 },
  '39': { code: 'OH', name: 'Ohio',           rate: 13.7 },
  '40': { code: 'OK', name: 'Oklahoma',       rate: 16.0 },
  '41': { code: 'OR', name: 'Oregon',         rate: 11.0 },
  '42': { code: 'PA', name: 'Pennsylvania',   rate: 11.2 },
  '44': { code: 'RI', name: 'Rhode Island',   rate: 11.4 },
  '45': { code: 'SC', name: 'South Carolina', rate: 13.7 },
  '46': { code: 'SD', name: 'South Dakota',   rate: 11.0 },
  '47': { code: 'TN', name: 'Tennessee',      rate: 13.7 },
  '48': { code: 'TX', name: 'Texas',          rate: 14.0 },
  '49': { code: 'UT', name: 'Utah',           rate:  9.6 },
  '50': { code: 'VT', name: 'Vermont',        rate: 10.2 },
  '51': { code: 'VA', name: 'Virginia',       rate:  9.8 },
  '53': { code: 'WA', name: 'Washington',     rate: 10.7 },
  '54': { code: 'WV', name: 'West Virginia',  rate: 14.0 },
  '55': { code: 'WI', name: 'Wisconsin',      rate:  9.6 },
  '56': { code: 'WY', name: 'Wyoming',        rate:  9.4 },
};
